#!/usr/bin/env python3
import sys
import os
from sense_hat import SenseHat
from time import sleep

sense = SenseHat()
sense.set_rotation(180)
sense.low_light = True

red   = [255,   0,  0]
green = [  0, 255,  0]
blue  = [  0,   0,255]


def timer(s):
    display = [blue for i in range(64)]
    sense.set_pixels(display)
    
    for i in range(0, 64):
        sleep(s/64)
        display[i] = green
        sense.set_pixels(display)
    
    sense.clear(red)
    sleep(0.1)
    sense.clear()


os.system("echo Running Timer")
num = sys.argv[1]
timer(int(num))
