#!/usr/bin/env python3
import sys
import subprocess
import threading
from timer import Timer
from cam import Cam
from sense_hat import SenseHat
from time import sleep

sense = SenseHat()
sense.set_rotation(180)
sense.low_light = True

subprocess.call("gphoto2 --set-config datetime=now", shell=True)
command = "./cam-trigger.sh"

num = sys.argv[1]

timer = Timer()
timer_thread = threading.Thread(target=timer.run, args=(int(num),sense))

timer_thread.start()
cam = subprocess.call(command, shell=True)

run = True
while(run):
    for event in sense.stick.get_events():
        if(event.action == "pressed"):
            if(event.direction == "middle"):
                timer.terminate()
                cam.terminate()
                subprocess.call("./mv2dir.sh", shell=True)
                sense.clear()
                run = False
